name: Betradar Update
on:
  schedule:
    - cron: '*/15 * * * *' # 15 percenként fut le
  workflow_dispatch:
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with: { python-version: '3.9' }
      - run: pip install selenium webdriver-manager
      - run: python bot.py
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
